enum language_enum {
  en
  fr
}

enum module_type {
  "1.2"
  2004
}

enum role_enum {
  owner
  member
}

table collection_translations {
  collectionId text [not null]
  language language_enum [not null]
  default boolean [not null]
  name text [not null]
  description text [not null]

  indexes {
    (collectionId, language) [pk]
  }
}

table collections {
  id text [pk, not null]
  teamId text [not null]
}

table collections_to_courses {
  collectionId text [not null]
  courseId text [not null]

  indexes {
    (collectionId, courseId) [pk]
  }
}

table course_translations {
  courseId text [not null]
  language language_enum [not null]
  default boolean [not null]
  name text [not null]
  description text [not null]

  indexes {
    (courseId, language) [pk]
  }
}

table courses {
  id text [pk, not null]
  teamId text [not null]
  completionStatus text [not null, default: `'passed'`]
}

table keys {
  id text [pk, not null]
  teamId text [not null]
  name text [not null]
  key text [not null]
}

table learners {
  id text [pk, not null]
  courseId text [not null]
  moduleId text
  email text [not null]
  firstName text [not null]
  lastName text [not null]
  completedAt "timestamp with time zone" [default: `null`]
  startedAt "timestamp with time zone" [default: `null`]
  data json [not null, default: `{}`]

  indexes {
    (courseId, email) [name: 'unq_learner', unique]
  }
}

table modules {
  id text [pk, not null]
  courseId text [not null]
  language language_enum [not null]
  type module_type [not null]
  versionNumber integer [not null, default: 1]
}

table sessions {
  id text [pk, not null]
  userId text [not null]
  expiresAt "timestamp with time zone" [not null]
}

table team_translations {
  teamId text [not null]
  language language_enum [not null]
  default boolean [not null]
  name text [not null]
  logo text
  favicon text

  indexes {
    (teamId, language) [pk]
  }
}

table teams {
  id text [pk, not null]
  customDomain text [unique]
  resendDomainId text
}

table users {
  id text [pk, not null]
  email text [not null, unique]
  googleId text [unique]
}

table users_to_teams {
  userId text [not null]
  teamId text [not null]
  role role_enum [not null, default: `'member'`]

  indexes {
    (userId, teamId) [pk]
  }
}

ref: collection_translations.collectionId > collections.id

ref: collections.teamId - teams.id

ref: collections_to_courses.collectionId > collections.id

ref: collections_to_courses.courseId > courses.id

ref: course_translations.courseId > courses.id

ref: courses.teamId > teams.id

ref: keys.teamId > teams.id

ref: learners.moduleId > modules.id

ref: learners.courseId - courses.id

ref: modules.courseId > courses.id

ref: sessions.userId - users.id

ref: team_translations.teamId > teams.id

ref: users_to_teams.userId > users.id

ref: users_to_teams.teamId > teams.id